/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dFCW3EJJak7e5FJ1Eb9ZNV
// Component: uXDeFc-2K0r3
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import YouTube from "@plasmicpkgs/react-youtube";
import { useScreenVariants as useScreenVariants_3Kid9VNeHn18 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 3kid9VNeHn18/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: dFCW3EJJak7e5FJ1Eb9ZNV/projectcss
import sty from "./PlasmicLanding.module.css"; // plasmic-import: uXDeFc-2K0r3/css
import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: oZi9B7lZCf0u/icon
import VectorSvgIcon from "./icons/PlasmicIcon__VectorSvg"; // plasmic-import: IxwY_TPA0zLe/icon
import SunFillSvgIcon from "./icons/PlasmicIcon__SunFillSvg"; // plasmic-import: AeZnRHxKnsBB/icon
import Vector1SvgIcon from "./icons/PlasmicIcon__Vector1Svg"; // plasmic-import: TY0YSLACzw09/icon
import GeoAltFill1SvgIcon from "./icons/PlasmicIcon__GeoAltFill1Svg"; // plasmic-import: YEWPN-2nVWdu/icon
import EnvelopeFill1SvgIcon from "./icons/PlasmicIcon__EnvelopeFill1Svg"; // plasmic-import: yiqTHAMM2X5j/icon
import Linkedin2SvgIcon from "./icons/PlasmicIcon__Linkedin2Svg"; // plasmic-import: 6HNgcahnQu82/icon
import Facebook2SvgIcon from "./icons/PlasmicIcon__Facebook2Svg"; // plasmic-import: IENMmqVlMhTI/icon
import ArrowUpRightCircleFill2SvgIcon from "./icons/PlasmicIcon__ArrowUpRightCircleFill2Svg"; // plasmic-import: pCYqUEbGa2Pj/icon

createPlasmicElementProxy;

export const PlasmicLanding__VariantProps = new Array();

export const PlasmicLanding__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLanding__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,
        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_3Kid9VNeHn18()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"homePage"}
          data-plasmic-override={overrides.homePage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.homePage
          )}
        >
          <div
            data-plasmic-name={"landingPage"}
            data-plasmic-override={overrides.landingPage}
            className={classNames(projectcss.all, sty.landingPage)}
          >
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  data-plasmic-name={"logo"}
                  data-plasmic-override={overrides.logo}
                  className={classNames(projectcss.all, projectcss.a, sty.logo)}
                  component={Link}
                  href={"#"}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__htcd7)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"298px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/copy_of_excell_website/images/layer2.svg",
                      fullWidth: 220.00169372558594,
                      fullHeight: 80.00094604492188,
                      aspectRatio: 2.75
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__fpJqA)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  src={{
                    src: "/plasmic/copy_of_excell_website/images/xLgSvg2.svg",
                    fullWidth: 24,
                    fullHeight: 25,
                    aspectRatio: 0.96
                  }}
                />
              }
              forceOpenMenu={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              }
              itemsGap={
                hasVariant(globalVariants, "screen", "mobileOnly") ? 48 : 48
              }
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__mJgCd
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"solution2"}
                    data-plasmic-override={overrides.solution2}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.solution2
                    )}
                    component={Link}
                    href={`/solutions`}
                    platform={"nextjs"}
                  >
                    {"Solution"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__nC64U
                    )}
                    component={Link}
                    href={`/projects`}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"logo2"}
                    data-plasmic-override={overrides.logo2}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.logo2
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__dOfup)}
                      displayHeight={"64px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"298px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/copy_of_excell_website/images/excellVerticalLogoPng.png",
                        fullWidth: 987,
                        fullHeight: 1002,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__sjVxj
                    )}
                    component={Link}
                    href={`/about`}
                    platform={"nextjs"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___032Zt
                    )}
                    component={Link}
                    href={`/learn`}
                    platform={"nextjs"}
                  >
                    {"Learn"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hc5Fu
                    )}
                    component={Link}
                    href={`/contact`}
                    platform={"nextjs"}
                  >
                    {"Contact Us"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__syn6I)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  src={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? {
                          src: "/plasmic/copy_of_excell_website/images/hamburgerMenuSvg.svg",
                          fullWidth: 24,
                          fullHeight: 25,
                          aspectRatio: 0.96
                        }
                      : undefined
                  }
                  width={"32"}
                />
              }
              responsiveBreakpoint={768}
            />

            <div className={classNames(projectcss.all, sty.freeBox__bAugT)}>
              <div
                data-plasmic-name={"headerTxt"}
                data-plasmic-override={overrides.headerTxt}
                className={classNames(projectcss.all, sty.headerTxt)}
              >
                <div className={classNames(projectcss.all, sty.column__zv8A4)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ln1UU)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__iv5V)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "223px"
                          : "317px"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"16px"}
                      loading={"lazy"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__uRbxU
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                        <React.Fragment>
                          <React.Fragment>
                            {"Democratizing access to "}
                          </React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Clean, Sustainable, Renewable Energy"}
                          </span>
                        </React.Fragment>
                      ) : (
                        <React.Fragment>
                          <React.Fragment>
                            {"Democratizing Access to \n"}
                          </React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Clean, Sustainable, Renewable Energy"}
                          </span>
                        </React.Fragment>
                      )}
                    </h1>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"taglineTxt"}
                data-plasmic-override={overrides.taglineTxt}
                className={classNames(projectcss.all, sty.taglineTxt)}
              >
                <div className={classNames(projectcss.all, sty.column__bfOZd)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1GX6D)}
                  >
                    <h5
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.text
                      )}
                    >
                      {"Better Energy. Better Solution"}
                    </h5>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"btns2"}
                data-plasmic-override={overrides.btns2}
                className={classNames(projectcss.all, sty.btns2)}
              >
                <div className={classNames(projectcss.all, sty.column__qOtLr)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hV4Q2
                    )}
                    component={Link}
                    href={`/solutions`}
                    platform={"nextjs"}
                  >
                    {"Find your Solar Solution"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.column__i2Mjc)}>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___7D9Vj
                    )}
                    component={Link}
                    href={`/get-solar-2`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xFlih)}
                      displayHeight={"24px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"24px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/copy_of_excell_website/images/lightningChargeFillSvg.svg",
                        fullWidth: 24,
                        fullHeight: 24,
                        aspectRatio: 1
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pjwkx
                      )}
                    >
                      {"Get Solar Now"}
                    </div>
                  </Stack__>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
            id={"explore-section"}
          >
            <div
              data-plasmic-name={"about"}
              data-plasmic-override={overrides.about}
              className={classNames(projectcss.all, sty.about)}
            >
              <div className={classNames(projectcss.all, sty.column__lpWG)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__lxEqX)}
                  triggerOnce={true}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___5MFnv
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"What"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {" "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"difference"}
                      </span>
                      <React.Fragment>{" do we make?"}</React.Fragment>
                    </React.Fragment>
                  </h1>
                </Reveal>
                <div
                  data-plasmic-name={"text2"}
                  data-plasmic-override={overrides.text2}
                  className={classNames(projectcss.all, sty.text2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vB58Q
                    )}
                  >
                    {
                      "We don\u2019t just install solar panels\u2014we solve energy problems. Excell Energy empowers customers with innovative, financially smart, and tech-forward solar solutions."
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(projectcss.all, sty.button)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__xRqpi)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__mDfG
                      )}
                      component={Link}
                      href={`/about`}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oubg3
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"About Excell Energy"}
                          </span>
                        </React.Fragment>
                      </div>
                      <ArrowRightIcon
                        className={classNames(projectcss.all, sty.svg__bTfPx)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__orkig)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kt4AG)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "267px"
                      : "629px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "450px"
                      : "730px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/copy_of_excell_website/images/specialistTechnicianProfessionalEngineerWithLaptopTabletMaintenanceCheckingInstallingSolarRoofPanelFactoryRooftopSunlightEngineersHoldingTabletCheckSolarRoofJpg.jpg",
                    fullWidth: 7952,
                    fullHeight: 5304,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"projects"}
              data-plasmic-override={overrides.projects}
              className={classNames(projectcss.all, sty.projects)}
            >
              <div className={classNames(projectcss.all, sty.column___80UXm)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jQCg3)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                />

                {(() => {
                  const child$Props = {
                    arrows: false,
                    autoplay: true,
                    autoplaySpeed: 0,
                    beforeChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "currentSlide",
                        ["sliderCarousel2", "currentSlide"],
                        SliderWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    centerMode: true,
                    className: classNames(
                      "__wab_instance",
                      sty.sliderCarousel2
                    ),
                    cssEase: "linear",
                    dots: false,
                    initialSlide: generateStateValueProp($state, [
                      "sliderCarousel2",
                      "currentSlide"
                    ]),
                    pauseOnFocus: true,
                    ref: ref => {
                      $refs["sliderCarousel2"] = ref;
                    },
                    sliderScopeClassName: sty["sliderCarousel2__slider"],
                    speed: 3000
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "currentSlide",
                        plasmicStateName: "sliderCarousel2.currentSlide"
                      }
                    ],

                    [],
                    SliderWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <SliderWrapper
                      data-plasmic-name={"sliderCarousel2"}
                      data-plasmic-override={overrides.sliderCarousel2}
                      {...child$Props}
                    >
                      <div
                        data-plasmic-name={"maintenance"}
                        data-plasmic-override={overrides.maintenance}
                        className={classNames(projectcss.all, sty.maintenance)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__xptF0)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/settingsGif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hxOfh
                          )}
                        >
                          {"Negligible Maintenance"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"investment"}
                        data-plasmic-override={overrides.investment}
                        className={classNames(projectcss.all, sty.investment)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__bpLzw)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/safeGif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oiWhr
                          )}
                        >
                          {"Safe Investment"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"upgradeProperty"}
                        data-plasmic-override={overrides.upgradeProperty}
                        className={classNames(
                          projectcss.all,
                          sty.upgradeProperty
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__dX6B6)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/moveInGif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p122C
                          )}
                        >
                          {"Upgrade Property"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"co2"}
                        data-plasmic-override={overrides.co2}
                        className={classNames(projectcss.all, sty.co2)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__voBnC)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/co2Gif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vJgRt
                          )}
                        >
                          {"Reduce Carbon Footprint"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"saveThePlanet"}
                        data-plasmic-override={overrides.saveThePlanet}
                        className={classNames(
                          projectcss.all,
                          sty.saveThePlanet
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__lqTeI)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/organicGif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tKh4X
                          )}
                        >
                          {"Save the Planet"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"everyone"}
                        data-plasmic-override={overrides.everyone}
                        className={classNames(projectcss.all, sty.everyone)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___8Fcnx)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/systemRegular199AttributionHoverAttributionGif.gif",
                            fullWidth: 400,
                            fullHeight: 400,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bLdK
                          )}
                        >
                          {"For Everyone"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"lowerEnergyBill"}
                        data-plasmic-override={overrides.lowerEnergyBill}
                        className={classNames(
                          projectcss.all,
                          sty.lowerEnergyBill
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__tRbVh)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "262px"
                              : "283px"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"646px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "276px"
                              : "605px"
                          }
                          src={{
                            src: "/plasmic/copy_of_excell_website/images/renewableEnergyGif.gif",
                            fullWidth: 372,
                            fullHeight: 372,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nI7W3
                          )}
                        >
                          {"Lower Energy Bill\n"}
                        </div>
                      </div>
                    </SliderWrapper>
                  );
                })()}
                <div className={classNames(projectcss.all, sty.freeBox__l78Vw)}>
                  <YouTube
                    data-plasmic-name={"youTube"}
                    data-plasmic-override={overrides.youTube}
                    className={classNames("__wab_instance", sty.youTube)}
                    modestbranding={false}
                    rel={false}
                    videoId={"0E0APu6hNZk"}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__cvH7F)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___6ATnf)}
                  duration={1500}
                  effect={"fade"}
                  triggerOnce={true}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__mqNhp
                    )}
                  >
                    {"Why Solar?"}
                  </h1>
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__yLzFe)}
                  triggerOnce={true}
                >
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__cTjZ)}
                    triggerOnce={true}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__kipIs
                      )}
                    >
                      {"Real Projects,\nReal Impact"}
                    </h1>
                  </Reveal>
                </Reveal>
                <div className={classNames(projectcss.all, sty.freeBox__bgBs0)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1U5Sw
                    )}
                  >
                    {
                      "Get long-term value, fast. Solar energy cuts your electricity bills, lowers your carbon footprint, and gives you control of your energy future.\r"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  className={classNames(projectcss.all, sty.button3)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__hJVw4)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aw9KW
                      )}
                      component={Link}
                      href={`/projects`}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3ZsI
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Explore our Portfolio"}
                          </span>
                        </React.Fragment>
                      </div>
                      <ArrowRightIcon
                        className={classNames(projectcss.all, sty.svg__ddChR)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"learn"}
              data-plasmic-override={overrides.learn}
              className={classNames(projectcss.all, sty.learn)}
            >
              <div className={classNames(projectcss.all, sty.column___1TOy6)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cMyaH)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "267px"
                      : "629px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "450px"
                      : "730px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/copy_of_excell_website/images/youngAsianFemaleInspectorEngineerTouchingCheckingOperationPhotovoltaicSolarPanelOutdoorStationHoldingLaptopComputerLookingCameraWithSmileCopySpaceJpg.jpg",
                    fullWidth: 6048,
                    fullHeight: 4024,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__n0Gbv)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__zybF7)}
                  triggerOnce={true}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__vzIVb
                    )}
                  >
                    {"Why go Solar now?"}
                  </h1>
                </Reveal>
                <div
                  data-plasmic-name={"text6"}
                  data-plasmic-override={overrides.text6}
                  className={classNames(projectcss.all, sty.text6)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__so7Jl
                    )}
                  >
                    {
                      "We don\u2019t just install solar panels\u2014we solve energy problems. Excell Energy empowers customers with innovative, financially smart, and tech-forward solar solutions."
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames(projectcss.all, sty.button2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__niJ3N)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kc0Ii
                      )}
                      component={Link}
                      href={`/learn`}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iiIfa
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Learn more about Solar"}
                          </span>
                        </React.Fragment>
                      </div>
                      <ArrowRightIcon
                        className={classNames(projectcss.all, sty.svg__w6Xg8)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"contactUs"}
              data-plasmic-override={overrides.contactUs}
              className={classNames(projectcss.all, sty.contactUs)}
            >
              <div className={classNames(projectcss.all, sty.column__p9ViC)}>
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__psl6A)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__qJNtO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nhElg
                        )}
                      >
                        <VectorSvgIcon
                          className={classNames(projectcss.all, sty.svg__z7QL3)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qvrDk
                        )}
                      >
                        <SunFillSvgIcon
                          className={classNames(projectcss.all, sty.svg__ymJwM)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9Chkt
                        )}
                      >
                        <Vector1SvgIcon
                          className={classNames(projectcss.all, sty.svg__cKjs)}
                          role={"img"}
                        />
                      </div>
                    </Stack__>
                  </div>
                </div>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__duyY)}
                  duration={1500}
                  effect={"fade"}
                  triggerOnce={true}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__vPa8V
                    )}
                  >
                    {"Why Solar?"}
                  </h1>
                </Reveal>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__dhfGm)}
                  triggerOnce={true}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__zYg51
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 300 }}
                      >
                        {"Connect with us and"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Get Free Consultation"}
                      </span>
                    </React.Fragment>
                  </h1>
                </Reveal>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iYsmv)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gu7Ll
                    )}
                  >
                    {
                      "Ready to make the switch to solar? Let our experts guide you in finding the best energy solution for your business or industry."
                    }
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___9S2Xc
                    )}
                    component={Link}
                    href={`/get-solar`}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___08Cwr
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Send your Inquiry Today!"}
                        </span>
                      </React.Fragment>
                    </div>
                  </PlasmicLink__>
                </Stack__>
              </div>
            </div>
          </div>
          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__xhQps)}>
              <div
                data-plasmic-name={"section5"}
                data-plasmic-override={overrides.section5}
                className={classNames(projectcss.all, sty.section5)}
              >
                <div
                  data-plasmic-name={"brandLogo3"}
                  data-plasmic-override={overrides.brandLogo3}
                  className={classNames(projectcss.all, sty.brandLogo3)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xx1AP)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "50%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"240px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/copy_of_excell_website/images/excellHorizontalLogoPng.png",
                      fullWidth: 2001,
                      fullHeight: 706,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"section6"}
                    data-plasmic-override={overrides.section6}
                    className={classNames(projectcss.all, sty.section6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___5ZCxv)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gtTdh
                        )}
                      >
                        <h4
                          data-plasmic-name={"h4"}
                          data-plasmic-override={overrides.h4}
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4
                          )}
                        >
                          {"Better Energy. Better Business."}
                        </h4>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ieFf
                          )}
                        >
                          {
                            "We help businesses thrive by turning unused spaces into energy-saving assets. Our end-to-end solar solutions\u2014from expert energy assessments to premium installations and lifetime support\u2014are built for long-term value, reliability, and sustainability."
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3I3G8
                          )}
                        >
                          {
                            "\u00a9 Copyright 2025 Excell Energy and Powergen Inc. All rights reserved."
                          }
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___5Vdi)}
                    >
                      <div
                        data-plasmic-name={"whereToFindUs3"}
                        data-plasmic-override={overrides.whereToFindUs3}
                        className={classNames(
                          projectcss.all,
                          sty.whereToFindUs3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__p3Fml
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__rMpaf
                            )}
                          >
                            {"Where to find us?"}
                          </h5>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y22Gt
                          )}
                        >
                          <GeoAltFill1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fansX
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yMtXd
                            )}
                          >
                            {
                              "Unit 2618, 26th flr, High Street South Corporate Plaza Tower 1 26th St, cor 9th Ave, 1634 Taguig, Philippines"
                            }
                          </div>
                        </Stack__>
                      </div>
                      <div
                        data-plasmic-name={"connectWithUs4"}
                        data-plasmic-override={overrides.connectWithUs4}
                        className={classNames(
                          projectcss.all,
                          sty.connectWithUs4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eLyT
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__ryWyz
                            )}
                          >
                            {"Connect with us!"}
                          </h5>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vH4SK
                          )}
                        >
                          <EnvelopeFill1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9Zqd6
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link___8DtB
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"solutions@excell.energy"}
                          </PlasmicLink__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ouSjF
                          )}
                        >
                          <Linkedin2SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__usj9B
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__ewjKg
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"Excell Energy and PowerGen Corp."}
                          </PlasmicLink__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hqCnb
                          )}
                        >
                          <Facebook2SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___3ZFsg
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__jg77
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"Excell Energy and PowerGen Corp."}
                          </PlasmicLink__>
                        </Stack__>
                      </div>
                      <div
                        data-plasmic-name={"getSolar3"}
                        data-plasmic-override={overrides.getSolar3}
                        className={classNames(projectcss.all, sty.getSolar3)}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fp7DO
                          )}
                        >
                          <Stack__
                            as={PlasmicLink__}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__l4Lva
                            )}
                            component={Link}
                            href={`/get-solar`}
                            platform={"nextjs"}
                          >
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5__nwm9Q
                              )}
                            >
                              {"Get Solar"}
                            </h5>
                            <ArrowUpRightCircleFill2SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__x5PYp
                              )}
                              role={"img"}
                            />
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  homePage: [
    "homePage",
    "landingPage",
    "navigationBar",
    "logo",
    "solution2",
    "logo2",
    "headerTxt",
    "taglineTxt",
    "text",
    "btns2",
    "content",
    "about",
    "text2",
    "button",
    "projects",
    "sliderCarousel2",
    "maintenance",
    "investment",
    "upgradeProperty",
    "co2",
    "saveThePlanet",
    "everyone",
    "lowerEnergyBill",
    "youTube",
    "button3",
    "learn",
    "text6",
    "button2",
    "contactUs",
    "columns",
    "footer",
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],

  landingPage: [
    "landingPage",
    "navigationBar",
    "logo",
    "solution2",
    "logo2",
    "headerTxt",
    "taglineTxt",
    "text",
    "btns2"
  ],

  navigationBar: ["navigationBar", "logo", "solution2", "logo2"],
  logo: ["logo"],
  solution2: ["solution2"],
  logo2: ["logo2"],
  headerTxt: ["headerTxt"],
  taglineTxt: ["taglineTxt", "text"],
  text: ["text"],
  btns2: ["btns2"],
  content: [
    "content",
    "about",
    "text2",
    "button",
    "projects",
    "sliderCarousel2",
    "maintenance",
    "investment",
    "upgradeProperty",
    "co2",
    "saveThePlanet",
    "everyone",
    "lowerEnergyBill",
    "youTube",
    "button3",
    "learn",
    "text6",
    "button2",
    "contactUs",
    "columns"
  ],

  about: ["about", "text2", "button"],
  text2: ["text2"],
  button: ["button"],
  projects: [
    "projects",
    "sliderCarousel2",
    "maintenance",
    "investment",
    "upgradeProperty",
    "co2",
    "saveThePlanet",
    "everyone",
    "lowerEnergyBill",
    "youTube",
    "button3"
  ],

  sliderCarousel2: [
    "sliderCarousel2",
    "maintenance",
    "investment",
    "upgradeProperty",
    "co2",
    "saveThePlanet",
    "everyone",
    "lowerEnergyBill"
  ],

  maintenance: ["maintenance"],
  investment: ["investment"],
  upgradeProperty: ["upgradeProperty"],
  co2: ["co2"],
  saveThePlanet: ["saveThePlanet"],
  everyone: ["everyone"],
  lowerEnergyBill: ["lowerEnergyBill"],
  youTube: ["youTube"],
  button3: ["button3"],
  learn: ["learn", "text6", "button2"],
  text6: ["text6"],
  button2: ["button2"],
  contactUs: ["contactUs", "columns"],
  columns: ["columns"],
  footer: [
    "footer",
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],

  section5: [
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],

  brandLogo3: [
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],

  section6: ["section6", "h4", "whereToFindUs3", "connectWithUs4", "getSolar3"],
  h4: ["h4"],
  whereToFindUs3: ["whereToFindUs3"],
  connectWithUs4: ["connectWithUs4"],
  getSolar3: ["getSolar3"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLanding__ArgProps,
          internalVariantPropNames: PlasmicLanding__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLanding__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homePage") {
    func.displayName = "PlasmicLanding";
  } else {
    func.displayName = `PlasmicLanding.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth(WrappedComponent) {
  const WithUsePlasmicAuthComponent = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "dFCW3EJJak7e5FJ1Eb9ZNV"
    });
    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicLanding = Object.assign(
  // Top-level PlasmicLanding renders the root element
  withUsePlasmicAuth(makeNodeComponent("homePage")),
  {
    // Helper components rendering sub-elements
    landingPage: makeNodeComponent("landingPage"),
    navigationBar: makeNodeComponent("navigationBar"),
    logo: makeNodeComponent("logo"),
    solution2: makeNodeComponent("solution2"),
    logo2: makeNodeComponent("logo2"),
    headerTxt: makeNodeComponent("headerTxt"),
    taglineTxt: makeNodeComponent("taglineTxt"),
    text: makeNodeComponent("text"),
    btns2: makeNodeComponent("btns2"),
    content: makeNodeComponent("content"),
    about: makeNodeComponent("about"),
    text2: makeNodeComponent("text2"),
    button: makeNodeComponent("button"),
    projects: makeNodeComponent("projects"),
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    maintenance: makeNodeComponent("maintenance"),
    investment: makeNodeComponent("investment"),
    upgradeProperty: makeNodeComponent("upgradeProperty"),
    co2: makeNodeComponent("co2"),
    saveThePlanet: makeNodeComponent("saveThePlanet"),
    everyone: makeNodeComponent("everyone"),
    lowerEnergyBill: makeNodeComponent("lowerEnergyBill"),
    youTube: makeNodeComponent("youTube"),
    button3: makeNodeComponent("button3"),
    learn: makeNodeComponent("learn"),
    text6: makeNodeComponent("text6"),
    button2: makeNodeComponent("button2"),
    contactUs: makeNodeComponent("contactUs"),
    columns: makeNodeComponent("columns"),
    footer: makeNodeComponent("footer"),
    section5: makeNodeComponent("section5"),
    brandLogo3: makeNodeComponent("brandLogo3"),
    section6: makeNodeComponent("section6"),
    h4: makeNodeComponent("h4"),
    whereToFindUs3: makeNodeComponent("whereToFindUs3"),
    connectWithUs4: makeNodeComponent("connectWithUs4"),
    getSolar3: makeNodeComponent("getSolar3"),
    // Metadata about props expected for PlasmicLanding
    internalVariantProps: PlasmicLanding__VariantProps,
    internalArgProps: PlasmicLanding__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLanding;
/* prettier-ignore-end */
