/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dFCW3EJJak7e5FJ1Eb9ZNV
// Component: S-OKsjQ2Ooxo
import * as React from "react";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: dFCW3EJJak7e5FJ1Eb9ZNV/projectcss
import sty from "./PlasmicYearDivider.module.css"; // plasmic-import: S-OKsjQ2Ooxo/css
import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: 0xWx5xDXrEv2/icon

createPlasmicElementProxy;

export const PlasmicYearDivider__VariantProps = new Array();

export const PlasmicYearDivider__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicYearDivider__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"yearDivider"}
      data-plasmic-override={overrides.yearDivider}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.yearDivider
      )}
    >
      <h2
        data-plasmic-name={"yearHeading"}
        data-plasmic-override={overrides.yearHeading}
        className={classNames(
          projectcss.all,
          projectcss.h2,
          projectcss.__wab_text,
          sty.yearHeading
        )}
        id={"1"}
      >
        {"2024"}
      </h2>
      <Line2Icon
        data-plasmic-name={"divider"}
        data-plasmic-override={overrides.divider}
        className={classNames(projectcss.all, sty.divider)}
        role={"img"}
      />
    </Stack__>
  );
}

const PlasmicDescendants = {
  yearDivider: ["yearDivider", "yearHeading", "divider"],
  yearHeading: ["yearHeading"],
  divider: ["divider"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicYearDivider__ArgProps,
          internalVariantPropNames: PlasmicYearDivider__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicYearDivider__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "yearDivider") {
    func.displayName = "PlasmicYearDivider";
  } else {
    func.displayName = `PlasmicYearDivider.${nodeName}`;
  }
  return func;
}

export const PlasmicYearDivider = Object.assign(
  // Top-level PlasmicYearDivider renders the root element
  makeNodeComponent("yearDivider"),
  {
    // Helper components rendering sub-elements
    yearHeading: makeNodeComponent("yearHeading"),
    divider: makeNodeComponent("divider"),
    // Metadata about props expected for PlasmicYearDivider
    internalVariantProps: PlasmicYearDivider__VariantProps,
    internalArgProps: PlasmicYearDivider__ArgProps
  }
);

export default PlasmicYearDivider;
/* prettier-ignore-end */
